services:
  db:
    image: mariadb:lts
    restart: unless-stopped
    # user: "${UID}:${UID}"
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wpuser
      MARIADB_PASSWORD: wppass
      MARIADB_ROOT_PASSWORD: toor
    volumes:
      - ./db:/var/lib/mysql
      - ./sockets:/var/run/mysqld

  wordpress:
    # image: wordpress:php8.4-apache
    #user: "${UID}:${UID}"
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "80:80" # HTTP
    #network_mode: "host"
    environment:
      WORDPRESS_DB_HOST: localhost:/var/run/mysqld/mysqld.sock
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - ./init.sh:/init.sh:ro
      - ../php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ./wp:/var/www/html
      - ./sockets:/var/run/mysqld
    entrypoint: ["/init.sh"]
    command: ["apache2-foreground"]
    depends_on:
      - db

